### ISSUE TITLE
ThermalExpansion can't find CofHCore?

### ISSUE THREAD

**Issue by fogger** [agaricusb/ModAnalyzer#4]
`Mod allmods\ThermalExpansion-2.3.0.b5.zip is missing dependency: MinecraftForge,CoFHCore. Cannot continue`

**allmods contains**
- `ThermalExpansion-2.3.0.b5.zip`
- `CoFHCore-1.5.1.b5.jar`

**Comment by agaricusb** [comment]
A comma-separated dependency list.. I've seen another mod using this. Will have to check if Forge supports this. I special-cased the other instance of this. 

The thing with the "dependencies" key is that it specifies soft dependencies, in order to determine which mods to load first. But if the dep does not exist, it is ignored - by Forge/FML, but not ModAnalyzer (so literally any dependency string can be specified and the mod will normally load fine). requiredMods on the other hand is for hard dependencies. Need to see what I can do about this in ModAnalyzer, perhaps another special case or if possible a more general fix.

**Comment by fogger** [comment]
I found another one, but this time there is only a single reqDep

`Mod allmods\TreeCapitator.ML.1.5.1.r01.zip is missing dependency: mod_bspkrsCore. Cannot continue`

**allmods**
- `[1.5.1]bspkrsCorev2.02.zip`
- `TreeCapitator.ML.1.5.1.r01.zip`

**Comment by agaricusb** [comment]
Added fixes for these mods. Note you'll probably want the Forge version of TreeCapitator not ModLoader (allmods/[1.5.1]TreeCapitator.Forge.1.5.1.r01.Uni.CoreMod.jar vs TreeCapitator.ML.1.5.1.r01.zip)
